apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: supersecret
  init: |
     CREATE TABLE inportantdata (
     id int4 PRIMARY KEY,
     count int4 NOT NULL
     );

     INSERT INTO importantdata (id, count) VALUES (1, 0);
