apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "update", "get", "list", "watch", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "update", "get", "list", "watch", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingress"]
  verbs: ["create", "update", "get", "list", "watch", "patch", "delete"]
